id: P009318
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:04.705318
source_metadata:
  id: bdr:W12567
  title: འདུལ་བ་མདོ་རྩའི་འགྲེལ་པ་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར
  author: ''
  volumes:
    040983ba4f5044c1a85815c340d447c6:
      image_group_id: I1PD36365
      title: ''
      volume_number: 1
      total_pages: 1080
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
