id: IC4B5AF1B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T13:45:55+00:00'
last_modified: '2022-06-08T10:09:55.469475+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W12567
  title: འདུལ་བ་མདོ་རྩའི་འགྲེལ་པ་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    877B:
      image_group_id: I1PD36365
      title: ''
      total_pages: 1080
      order: 1
      base_file: 877B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
