id: IC4B5AF1B
legacy_id: P009318
ocr_import_info:
  bdrc_scan_id: W12567
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T13:38:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T13:21:21.529337+00:00'
last_modified: 2022-08-29 21:25:37.708957
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W12567
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW12567
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོ་རྩའི་འགྲེལ་པ་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར།
  author: མཚོ་སྣ་བ་ཤེས་རབ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9345000959276646
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD36365:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD36365
      total_pages: 1080
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD36365.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9345000959276646
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
